version: "3.8"

services:
  portfolio-client:
    image: haiou2003/my-photographer-portfolio-app-client:latest
    container_name: portfolio-client
    env_file:
      - ./client/.env.production
    restart: unless-stopped
    ports:
      - "3000:80"

    # ===== Networks configuration =====
    networks:
      - portfolio-net
      - reverse-proxy-net

    # ===== Resource limits =====
    mem_limit: 64m          # nginx chỉ cần vậy là dư
    memswap_limit: 64m      # KHÔNG cho swap
    cpus: "0.20"            # 20% CPU là đủ

    # Security & stability
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run

  portfolio-server:
    image: haiou2003/my-photographer-portfolio-app-server:latest
    container_name: portfolio-server
    env_file:
      - ./server/.env.production
    restart: unless-stopped
    ports:
      - "5000:5000"

    # ===== Networks configuration =====
    networks:
      - portfolio-net

    # ===== Resource limits =====
    mem_limit: 256m         # NodeJS production ổn định
    memswap_limit: 256m     # KHÔNG cho swap
    cpus: "0.70"            # ~70% CPU

    # Kill nếu vượt RAM (tránh treo Pi)
    oom_kill_disable: false

# ===== Global Networks Setup =====
networks:
  portfolio-net:
    name: portfolio-net
    external: true
  reverse-proxy-net:
    name: reverse-proxy-net
    external: true
